# src/infra/docker-compose.yml
version: '3.8'

services:
  app:
    build:
      context: ../..  # Go up to the project root
      dockerfile: src/infra/Dockerfile
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/database
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

volumes:
  pgdata:
